<?php

namespace Database\Seeders;

use App\Models\Vendor;
use Illuminate\Database\Seeder;

class VendorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $vendors = [
            [
                'name' => 'Tech Solutions Pvt Ltd',
                'contact_person' => 'Ramesh Kumar',
                'email' => 'contact@techsolutions.com',
                'phone' => '9876543210',
                'gst_no' => '24ABCDE1234F1Z5',
                'bank_name' => 'HDFC Bank',
                'account_number' => '50100123456789',
                'ifsc' => 'HDFC0001234',
                'address' => '101 Business Hub',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'country' => 'India',
                'postal_code' => '380015',
                'is_active' => true,
            ],
            [
                'name' => 'Global Supplies',
                'contact_person' => 'Priya Mehta',
                'email' => 'sales@globalsupplies.in',
                'phone' => '9123456780',
                'gst_no' => '24FGHIJ5678L1Z3',
                'bank_name' => 'ICICI Bank',
                'account_number' => '102345678901',
                'ifsc' => 'ICIC0004567',
                'address' => '22 Corporate Avenue',
                'city' => 'Surat',
                'state' => 'Gujarat',
                'country' => 'India',
                'postal_code' => '395007',
                'is_active' => true,
            ],
            [
                'name' => 'Office Needs India',
                'contact_person' => 'Sanjay Patel',
                'email' => 'info@officeneeds.in',
                'phone' => '9988776655',
                'gst_no' => '24KLMNO9012P1Z6',
                'bank_name' => 'Axis Bank',
                'account_number' => '918273645001',
                'ifsc' => 'UTIB0002345',
                'address' => '45 Industrial Estate',
                'city' => 'Vadodara',
                'state' => 'Gujarat',
                'country' => 'India',
                'postal_code' => '390001',
                'is_active' => true,
            ],
            [
                'name' => 'Digital Services LLP',
                'contact_person' => 'Anita Singh',
                'email' => 'accounts@digitalservices.com',
                'phone' => '9765432109',
                'gst_no' => '24PQRST3456U1Z7',
                'bank_name' => 'SBI',
                'account_number' => '332211445566',
                'ifsc' => 'SBIN0001234',
                'address' => '88 IT Park',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'country' => 'India',
                'postal_code' => '380054',
                'is_active' => true,
            ],
            [
                'name' => 'Smart Systems',
                'contact_person' => 'Vikram Joshi',
                'email' => 'support@smartsystems.in',
                'phone' => '9870012345',
                'gst_no' => '24UVWXY7890Z1Z2',
                'bank_name' => 'Kotak Bank',
                'account_number' => '700123456789',
                'ifsc' => 'KKBK0005678',
                'address' => '12 Technology Plaza',
                'city' => 'Rajkot',
                'state' => 'Gujarat',
                'country' => 'India',
                'postal_code' => '360001',
                'is_active' => true,
            ],
            [
                'name' => 'Cloud Hosting India',
                'contact_person' => 'Neha Shah',
                'email' => 'billing@cloudhosting.in',
                'phone' => '9825012345',
                'gst_no' => '24HOSTI1234A1Z9',
                'bank_name' => 'HDFC Bank',
                'account_number' => '600012345678',
                'ifsc' => 'HDFC0005678',
                'address' => '55 IT Tower',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'country' => 'India',
                'postal_code' => '380059',
                'is_active' => true,
            ],
            [
                'name' => 'Marketing Experts',
                'contact_person' => 'Akash Verma',
                'email' => 'hello@marketingexperts.in',
                'phone' => '9898989898',
                'gst_no' => '24MARKT5678B1Z5',
                'bank_name' => 'ICICI Bank',
                'account_number' => '800045678912',
                'ifsc' => 'ICIC0009876',
                'address' => '9 Commerce Centre',
                'city' => 'Mumbai',
                'state' => 'Maharashtra',
                'country' => 'India',
                'postal_code' => '400001',
                'is_active' => true,
            ],
            [
                'name' => 'Travel Hub',
                'contact_person' => 'Rahul Jain',
                'email' => 'bookings@travelhub.in',
                'phone' => '9811111111',
                'gst_no' => '24TRAVL9012C1Z8',
                'bank_name' => 'Axis Bank',
                'account_number' => '123456789012',
                'ifsc' => 'UTIB0001111',
                'address' => 'Airport Road',
                'city' => 'Delhi',
                'state' => 'Delhi',
                'country' => 'India',
                'postal_code' => '110001',
                'is_active' => true,
            ],
            [
                'name' => 'Training Academy',
                'contact_person' => 'Pooja Sharma',
                'email' => 'admin@trainingacademy.com',
                'phone' => '9755555555',
                'gst_no' => '24TRAIN5678D1Z1',
                'bank_name' => 'SBI',
                'account_number' => '987654321012',
                'ifsc' => 'SBIN0005678',
                'address' => 'Knowledge Park',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'country' => 'India',
                'postal_code' => '411001',
                'is_active' => true,
            ],
            [
                'name' => 'Furniture World',
                'contact_person' => 'Ketan Desai',
                'email' => 'sales@furnitureworld.in',
                'phone' => '9909009000',
                'gst_no' => '24FURNI1234E1Z2',
                'bank_name' => 'Bank of Baroda',
                'account_number' => '456789123456',
                'ifsc' => 'BARB0AHMEDX',
                'address' => 'SG Highway',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'country' => 'India',
                'postal_code' => '380060',
                'is_active' => true,
            ],
        ];

        foreach ($vendors as $vendor) {
            Vendor::create($vendor);
        }
    }
}
